# -*- coding: utf-8 -*-
"""Calculator.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1k00Po69Zw6TvvDUQ4I1RMO3SHyL02xAZ
"""

import math

print("Welcome to Calculator!")

def add(num1, num2):
  return num1 + num2

def subtract(num1, num2):
  return num1 - num2

def multiply(num1, num2):
  return num1 * num2

def divide(num1, num2):
  return num1 / num2

def modulo(num1, num2):
  return num1 % num2

def exponentiation(num1, num2):
  return num1 ** num2

def floor_division(num1, num2):
  return num1 // num2


def again():
  answer = input("\nDo you want to calculate anything else? (Yes / No) : ")

  if answer.lower() == "yes":
    calculate()

  elif answer.lower() == "no":
    print("\nOkay, Goodbye!")

  else:
    print("\nInvalid choice!")
    again() 

 
def calculate():

  
  def choices():
    print("\n+ for addition\n"
        "- for substraction\n"
        "* for multiplication\n"
        "/ for division\n"
        "% for finding the remainder\n"
        "** for exponential\n"
        "// for floor division\n\n")
  
  
  choices()  
  operations = ["+", "-", "*", "/", "%", "**", "//"] #List of possible operation symbols.
  operation = input("Please enter a valid operation: ") 

  while True:

    if operation in operations: #Checking if the input is valid or not.

      number_1 = float(input("Enter the first number: "))
      number_2 = float(input("Enter the second number: "))

      if operation == "+":
        result = add(number_1, number_2) 
        print(number_1, " + ", number_2, " = ", result)

      elif operation == "-":
        result = subtract(number_1, number_2)
        print(number_1, " - ", number_2, " = ", result)

      elif operation.lower() == "*":
        result = multiply(number_1, number_2) 
        print(number_1, " * ", number_2, " = ", result)

      elif operation == "/":
        result = divide(number_1, number_2) 
        print(number_1, " / ", number_2, " = ", result)

      elif operation == "%":
        result = modulo(number_1, number_2) 
        print(number_1, " % ", number_2, " = ", result)

      elif operation == "**":
        result = exponentiation(number_1, number_2)
        print(number_1, " ** ", number_2, " = ", result)

      elif operation == "//":
        result = floor_division(number_1, number_2) 
        print(number_1, " // ", number_2, " = ", result)
      break 

    else:
      print("\nThat is not a valid operation.")
      choices()
      operation = input("Please enter a valid operation: ")

  again() 
  
calculate()
